# Youtube parse channels settings
parser:
  # Turn on/off parser
  enabled: true
  # If skipMode: true, videos would't post to vk public and telegram, 
  # but store to app database, that items wouldn't be posted in the future
  skipMode: false
  # Interval for check RSS updates (seconds)
  interval: 120

# Proxy settings
proxy:
  # Turn on/off proxy
  enabled: false
  # Proxy URL, examples: 
  # "socks5://localhost:9050" (local tor socks5 proxy)
  # "http://proxy.com:3128" (some http proxy)
  url: ""

# Your post targets collection,
# without spaces, example: `postube`, `sciencevideos`
# define and create config for them: 
# cp ./config/tube.config.example.yaml ./config/TUBE_NAME.config.yaml
# **TUBE_NAME** is a name of the tube
tubes:
  - postube
  # - sciencevideos
  # - etcmoves

